### ISSUE TITLE
[BUG] docker image not available

### ISSUE THREAD

**Issue by juka19** [rodekruis/ada-collection#6]
### **Who notified us about the bug?**
Julian

### **Describe the bug**
The docker image is not available (nor is any other docker image by rodekruis on docker for that matter)

### **To Reproduce**
1. Go to [docker](https://hub.docker.com/r/rodekruis/ada-collection)
2. See error

### **Expected behavior**
docker image

### **Screenshots**
![image](https://user-images.githubusercontent.com/56269720/230778311-fad67c97-2a9f-4ffb-98bf-54c23acce6a7.png)

**Comment by jmargutt** [comment]
@juka19 our organizational account has been deactivated when Docker made it paid-only. You can now find the image at [jmargutti/ada-collection](https://hub.docker.com/r/jmargutti/ada-collection)

**Comment by jmargutt** [comment]
Issue closed.
